export const WORKPOSITIONS: string[] = [
  'Adminisztráció, Irodai munka',
  'Bank, Biztosítás, Bróker',
  'Cégvezetés, Menedzsment',
  "Egészségügy, Gyógyszeripar",
  "Építőipar, Ingatlan",
  "Értékesítés, Kereskedelem",
  "Fizikai, Segéd, Betanított munka",
  "Gyártás, Termelés",
  "HR, Munkaügy",
  "IT programozás, Fejlesztés",
  "IT üzemeltetés, Telekom",
  "Jog, Jogi tanácsadás",
  "Közigazgatás",
  "Marketing, Média, PR",
  "Mérnök",
  "Mezőgazdaság, Környezet",
  "Oktatás, Kutatás, Tudomány",
  "Pénzügy, Könyvelés",
  "Szakmunka",
  "Szállítás, Beszerzés, Logisztika",
  "Ügyfélszolgálat, Vevőszolgálat",
  "Üzleti támogató központok",
  "Vendéglátás, Idegenforgalom"
];
